# Generated by Django 4.1.2 on 2023-01-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0004_alter_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
