# Generated by Django 4.1.2 on 2023-01-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0010_remove_post_comment_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
