# Generated by Django 4.1.2 on 2023-01-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0012_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
