# Generated by Django 4.1.2 on 2023-01-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0016_alter_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='commented',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LikerApp.comment'),
        ),
    ]
