# Generated by Django 4.1.2 on 2023-01-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0018_remove_post_comment_remove_post_commented_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
