# Generated by Django 4.1.2 on 2023-03-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0029_remove_comment_user_alter_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag1',
            field=models.CharField(choices=[('Blogging', 'Blogging'), ('Writing', 'Writing'), ('Tips', 'Tips'), ('How-to', 'How-to'), ('Reviews', 'Reviews'), ('News', 'News'), ('Trends', 'Trends'), ('Opinion', 'Opinion'), ('Personal', 'Personal'), ('Stories', 'Stories'), ('Humor', 'Humor'), ('Inspiration', 'Inspiration'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty')], default=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag2',
            field=models.CharField(choices=[('Blogging', 'Blogging'), ('Writing', 'Writing'), ('Tips', 'Tips'), ('How-to', 'How-to'), ('Reviews', 'Reviews'), ('News', 'News'), ('Trends', 'Trends'), ('Opinion', 'Opinion'), ('Personal', 'Personal'), ('Stories', 'Stories'), ('Humor', 'Humor'), ('Inspiration', 'Inspiration'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty')], default=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag3',
            field=models.CharField(choices=[('Blogging', 'Blogging'), ('Writing', 'Writing'), ('Tips', 'Tips'), ('How-to', 'How-to'), ('Reviews', 'Reviews'), ('News', 'News'), ('Trends', 'Trends'), ('Opinion', 'Opinion'), ('Personal', 'Personal'), ('Stories', 'Stories'), ('Humor', 'Humor'), ('Inspiration', 'Inspiration'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty')], default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.nicepng.com%2Fourpic%2Fu2y3a9e6t4o0a9w7_profile-picture-default-png%2F&psig=AOvVaw0XZJRgHSQbfq2A0dfOcEzm&ust=1677998456366000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCKDf9b_Vwf0CFQAAAAAdAAAAABAE', null=True, upload_to='static/images'),
        ),
    ]
