# Generated by Django 4.1.2 on 2023-03-10 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0030_post_keywords_post_tag1_post_tag2_post_tag3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag1',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag3',
        ),
    ]
