# Generated by Django 4.1.2 on 2023-03-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0031_rename_tag1_post_tag_remove_post_tag2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
    ]
