# Generated by Django 4.1.2 on 2023-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0032_remove_post_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
