# Generated by Django 4.1.2 on 2023-01-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
