# Generated by Django 4.1.2 on 2023-01-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0015_alter_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
