# Generated by Django 4.1.2 on 2023-01-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0022_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
