# Generated by Django 4.1.2 on 2023-01-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LikerApp', '0027_comment_profile_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LikerApp.profile'),
        ),
    ]
